site_name: BiodiversityObservationNetworks.jl
repo_url: https://github.com/PoisotLab/BiodiversityObservationNetworks.jl
site_description: Julia package 
site_author: Michael D. Catchen

theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: default
    primary: teal
    accent: light blue

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - pymdownx.details
  - pymdownx.superfences

docs_dir: 'build'

nav:
  - Home: index.md
  - Vignettes: 
    - Overview: vignettes/overview.md
    - Entropize: vignettes/entropize.md
    - Uniqueness.jl: vignettes/uniqueness.md